//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AMA.DataLayer.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class NLog
    {
        public long Id { get; set; }
        public string Message { get; set; }
        public string Level { get; set; }
        public string Logger { get; set; }
        public string Application { get; set; }
        public string Callsite { get; set; }
        public string Exception { get; set; }
        public Nullable<System.DateTime> Logged { get; set; }
    }
}
