//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AMA.DataLayer.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class OfferBrand
    {
        public int Id { get; set; }
        public string BrandName { get; set; }
        public string Description { get; set; }
    }
}
