//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AMA.DataLayer.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public long ID { get; set; }
        public string MacID { get; set; }
        public string IPAddress { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public string ContractNumber { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    }
}
