//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AMA.DataLayer.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class VisitedUser
    {
        public int ID { get; set; }
        public string MacId { get; set; }
        public string IPAddress { get; set; }
        public Nullable<int> Count { get; set; }
        public Nullable<int> CatagoryID { get; set; }
        public string CatagoryPath { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string ProductTitle { get; set; }
        public string ProductUrl { get; set; }
        public string ImageUrl { get; set; }
        public string ProductId { get; set; }
        public Nullable<System.DateTime> LastVisitedDate { get; set; }
        public Nullable<bool> ClickedOnBuyNow { get; set; }
    }
}
